name: Makefile CI

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make dependences

    - name: Proyecto SMX
      run: make proyecto-smx	

    - name: Proyecto DAW
      run: make proyecto-daw	

    - name: Proyecto DAM
      run: make proyecto-dam	
      
    - name: Proyecto ASIR
      run: make proyecto-asir
      
    - uses: actions/upload-artifact@v4
      with:
        name: PCCFs
        path: PDFS/ #
        
    - uses: actions/create-release@v1
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
         tag_name: ${{ github.ref }}
         release_name: crust@v${{ github.ref }}
         draft: false
         prerelease: false
      
    - name: Lanzamiento
      run: echo ${{ github.sha }} > Release.txt
      
    - name: Subiendo Ficheros
      uses: softprops/action-gh-release@v2
      with:
          files: 
            Release.txt PDFS/PCCF_SENIA_DAM.pdf PDFS/PCCF_SENIA_SMX.pdf PDFS/PCCF_SENIA_DAW.pdf PDFS/PCCF_SENIA_ASIR.pdf


