name: Makefile CI

on:
  push:
    tags:
      - "*"
permissions:
  contents: write
  
jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make dependences

    - name: Proyecto SMX
      run: make proyecto-smx	

    - name: Proyecto DAW
      run: make proyecto-daw	

    - name: Proyecto DAM
      run: make proyecto-dam	
      
    - name: Proyecto ASIR
      run: make proyecto-asir
      
    - uses: actions/upload-artifact@v4
      with:
        name: PCCFs
        path: PDFS/ 
    - name: Comprobar existencia de los PDFs
      run: |
        test -f PDFS/PCCF_SENIA_SMX.pdf || (echo "Falta PCCF_SENIA_SMX.pdf" && exit 1)
        test -f PDFS/PCCF_SENIA_DAW.pdf || (echo "Falta PCCF_SENIA_DAW.pdf" && exit 1)
        test -f PDFS/PCCF_SENIA_DAM.pdf || (echo "Falta PCCF_SENIA_DAM.pdf" && exit 1)
        test -f PDFS/PCCF_SENIA_ASIR.pdf || (echo "Falta PCCF_SENIA_ASIR.pdf" && exit 1

  release:
    runs-on: ubuntu-latest
    needs: create-release
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: PCCFs
          path: downloaded/
      - name: Comprobar existencia de los PDFs
        run: |
          test -f downloaded/PCCF_SENIA_SMX.pdf || (echo "Falta downloaded/PCCF_SENIA_SMX.pdf" && exit 1)
          
      - name: Create GitHub Release with PDFs
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: |
            downloaded/PCCF_SENIA_DAM.pdf
            downloaded/PCCF_SENIA_SMX.pdf
            downloaded/PCCF_SENIA_DAW.pdf
            downloaded/PCCF_SENIA_ASIR.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    - name: Release with Notes
#      uses: softprops/action-gh-release@v2.3.2
#      with:
#        files: |
#          PDFS/PCCF_SENIA_DAM.pdf
#          PDFS/PCCF_SENIA_SMX.pdf
#          PDFS/PCCF_SENIA_DAW.pdf
#          PDFS/PCCF_SENIA_ASIR.pdf   
#      env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
