name: Makefile CI

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make dependences

    - name: Proyecto SMX
      run: make proyecto-smx	

    - name: Proyecto DAW
      run: make proyecto-daw	

    - name: Proyecto DAM
      run: make proyecto-dam	
      
    - name: Proyecto ASIR
      run: make proyecto-asir
      
    - uses: actions/upload-artifact@v4
      with:
        name: PCCFs
        path: PDFS/ #

    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: |
          PDFS/PCCF_SENIA_DAM.pdf
          PDFS/PCCF_SENIA_SMX.pdf
          PDFS/PCCF_SENIA_DAW.pdf
          PDFS/PCCF_SENIA_ASIR.pdf   
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
