name: Makefile CI

on:
  push:
    tags:
      - "*"

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make dependences

    - name: Proyecto SMX
      run: make proyecto-smx	

    - name: Proyecto DAW
      run: make proyecto-daw	

    - name: Proyecto DAM
      run: make proyecto-dam	
      
    - name: Proyecto ASIR
      run: make proyecto-asir
      
    - uses: actions/upload-artifact@v4
      with:
        name: PCCFs
        path: PDFS/ #

    - uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.MY_CUSTOM_TAG }}
        name: My Creative Name
        body: >
          This release actually changes the fabric of the reality, so be careful 
          while applying, as error in database migration, can irrecoverably wipe 
          some laws of physics.  
        files: >
          PDFS/PCCF_SENIA_DAM.pdf
          PDFS/PCCF_SENIA_SMX.pdf
          PDFS/PCCF_SENIA_DAW.pdf
          PDFS/PCCF_SENIA_ASIR.pdf
      
